language: ruby
rvm:
  - 2.4.1
addons:
  code_climate:
    repo_token:
      secure: "dxtcWB7El+xhgpJC9S2j9zdOSdteskv5P8akDPQUFhQ2gV7lwesODtnHQECAJ8mHFkkYBuvg7OGghoiewwma/QESBoW3NujfPtIuBqZ2GDavK5TQpMp2/ZtF9GBRHBjEDIz3MwKL/3DM2Y/XMnqVw5GLBpY9YkzLBNCcedcGf5MOa+X99MfoThljm9O3c4MXcIo+yXXLR9ShiTU0DxBsIZBW9ataDgn6aqOoKvYMO9vkqZRkV1rjdv4EBVmR8rNLuLD7jXcWauiQ65xeNSXNvRlvEzrl5MLZv/nr2Wwa22D5rJU1jaAXVNbGZZWp5K4pzqXZIov5VsKzJFYtegmCMI8HdHz4fbXE+1XqsJdDPIGE3pFVaASw0RKJmkxMSzeEFjMiCHES9McQI/VE/+TzXn8MemxUtzW7TFH6fpSfv4qNEjszyN/KmtPHsOPRcuugOvUmCvYdHkyTKOoTRW6xyDxCsLWcS1SSoI03ZTV6jyeZClu0RDxiUkYR2vOrGlXi9Oqq0hArPQGWfipev3RJQ2BujRLDcHHM2jNkdU1tsVp+D0PmB7ycv9j2w/JLkl8NtrBrT0Ms9s70w4yTGRlCh3NpjYcLHsk488JTXVnE4F0aDtSO0pzXWgomNjpcD0b4njCA7nr+mf++zQC4aquqpKM6D33+BtsX4tN6yDyRIto="
after_success:
  - bundle exec codeclimate-test-reporter
